---

- name: Debconf
  debconf:
    name: 'ldap-auth-config'
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ openldap_client_ldap_auth_config }}"

- name: Install Apt Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ openldap_client_apt_packages }}"

- name: Install python modules
  pip:
    name: "{{ item }}"
  with_items: "{{ openldap_client_pip_packages }}"

- name: Template nss and pam related files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - src: "nsswitch.conf"
      dest: "/etc/nsswitch.conf"
    - src: "common-session"
      dest: "/etc/pam.d/common-session"

- name: Template specified files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0644') }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    backup: "{{ item.backup|default('yes') }}"
  with_items: "{{ openldap_client_templates }}"

- name: Restart nscd
  service:
    name: nscd
    state: restarted
