---

- name: Debconf
  debconf:
    name: 'ldap-auth-config'
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: openldap_client_ldap_auth_config

- name: Install Apt Packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "libpam-ldap"
    - "nscd"

- name: Template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - src: "nsswitch.conf"
      dest: "/etc/nsswitch.conf"
    - src: "common-session"
      dest: "/etc/pam.d/common-session"

- name: Restart nscd
  service:
    name: nscd
    state: restarted