---

openldap_client_apt_packages:
  - "ldap-utils"
  - "libpam-ldap"
  - "nscd"
  - "libsasl2-dev"
  - "python-dev"
  - "libldap2-dev"
  - "libssl-dev"
  - "python-pip"
  - "dos2unix"

openldap_client_pip_packages:
  - "python-ldap"
  - "ssh-ldap-pubkey"

openldap_client_ldap_auth_config:
  - question: "ldap-auth-config/binddn"
    value: "cn=proxyuser,dc=example,dc=net"
    vtype: "string"
  - question: "ldap-auth-config/bindpw"
    value: "(password omitted)"
    vtype: "password"
  - question: "ldap-auth-config/dblogin"
    value: "false"
    vtype: "boolean"
  - question: "ldap-auth-config/dbrootlogin"
    value: "true"
    vtype: "boolean"
  - question: "ldap-auth-config/ldapns/base-dn"
    value: "dc=example,dc=net"
    vtype: "string"
  - question: "ldap-auth-config/ldapns/ldap-server"
    value: "ldapi:///"
    vtype: "string"
  - question: "ldap-auth-config/ldapns/ldap_version"
    value: "3"
    vtype: "select"
  - question: "ldap-auth-config/move-to-debconf"
    value: "true"
    vtype: "boolean"
  - question: "ldap-auth-config/override"
    value: "true"
    vtype: "boolean"
  - question: "ldap-auth-config/pam_password"
    value: "md5"
    vtype: "select"
  - question: "ldap-auth-config/rootbinddn"
    value: "cn=manager,dc=example,dc=net"
    vtype: "string"
  - question: "ldap-auth-config/rootbindpw"
    value: "(password omitted)"
    vtype: "password"

openldap_client_nsswitch_passwd: "compat"
openldap_client_nsswitch_group: "compat"
openldap_client_nsswitch_shadow: "compat"

openldap_client_pamd_session: []

openldap_client_templates:
  - src: "ldap_profile.sh.j2"
    dest: "/usr/local/bin/ldap_profile.sh"
    mode: "0755"
